### ISSUE TITLE
Show is played once, then it proceeds to new shot

### ISSUE THREAD

**Issue by st4ycool** [ekiefl/pooltool#103]
![image](https://github.com/ekiefl/pooltool/assets/17159323/efb5f816-9fd4-49c7-806d-0edb54c1ed57)
This is not true

**Comment by ekiefl** [comment]
Thank you @st4ycool. You're right, that doc was stale.

I've updated the wiki (https://github.com/ekiefl/pooltool/wiki) correspondingly. List of changes:

(1) reflect the actual behavior
(2) explain how shots _can_ be looped (spoiler: press _r_)
(3) add GIFs to show people visually what each of the controls do

Thanks for your interest in the project. I always assume that for each issue made, there's at least 10 people who encountered the problem but never said anything. So thanks!

**Comment by st4ycool** [comment]
Thank you!

Regards 'r' button - if shot is very fast or very slow, you won't be in time to tap R. Also, if you pocket the que ball, which is unexpected mostly of times, shot ends and you proceed to a new one, without chance to tap r or z if you are not really focused on it...

**Comment by ekiefl** [comment]
Yeah, I understand the issue you're talking about. You can always replay the shot by cycling through the shot history (press _n_ and _p_ for next and previous), however currently you can't undo a shot. It would be nice if you could press _z_ while in aim mode, I agree.
