### ISSUE TITLE
Cut induced throw and spin induced throw

### ISSUE THREAD

**Issue by st4ycool** [ekiefl/pooltool#107]
Hey hey. As I noticed, there is no deflection on a cue ball, when I try maximum side spin. 

I recreated this setup: https://youtu.be/h_x1XPqVBIM?t=90
and got totally different results.

I want to contribute, but I am terrible with physics. Could you give a direction on where to start from?

edit: sorry title is a little bit misleading.
Originally I wanted to ask about this part: https://youtu.be/h_x1XPqVBIM?t=490

**Comment by ekiefl** [comment]
Currently there is no cut-induced throw, spin-induced throw, or cue deflection from off-center hits.

If you want to contribute, you should read [this markdown file](https://github.com/ekiefl/pooltool/blob/main/pooltool/physics/resolve/README.md). If you're terrible with physics, that might be a problem, but all pull requests are welcome!

**Comment by st4ycool** [comment]
@ekiefl so nicely written manual! Thank you. But what about cut-induced throw, spin-induced throw, or cue deflection from off-center hits, how do you evaluate their complexity? Which one will be the easiest to start from?

**Comment by ekiefl** [comment]
Deflection is probably easiest.

Rather than using a physically derived model, you could write a heuristic based model that feels right. The more side spin, the more deflection.

**Comment by ekiefl** [comment]
Cut- and spin-induced throw was introduced in https://github.com/ekiefl/pooltool/pull/153 and cue ball deflection (squirt) was introduced in https://github.com/ekiefl/pooltool/pull/139 🥳
