### ISSUE TITLE
Getting "Can't instantiate abstract class Snooker with abstract method copy" when game_type=SNOOKER

### ISSUE THREAD

**Issue by st4ycool** [ekiefl/pooltool#110]
version: 0.2.2.1
[gist with stacktrace](https://gist.github.com/st4ycool/e598484f0df13db5c7c127a29c235b1c)

**Comment by ekiefl** [comment]
Can you `git pull`? I think I fixed this the other day.

**Comment by st4ycool** [comment]
Got you!
