### ISSUE TITLE
Better to install using pipx on macOS

### ISSUE THREAD

**Issue by gingerbeardman** [ekiefl/pooltool#151]
I installed using pipx and it just worked.

I couldn't get it to run after installing with pip, missing libraries and other problems.

IIRC Apple have locked some of the system python down so it's no longer advised to install using pip.

AFAIK pipx is recommended for installing apps, pip for frameworks

I'm not an expert :)

**Comment by ekiefl** [comment]
Thank you for sharing your installation experience. Glad that using pipx worked smoothly for you.

The problems you encountered when installing with pip are likely due to the specific Python environment on your system rather than an issue with pip itself (or with pooltool). On macOS, the system Python can have restrictions or conflicts because it's managed by the operating system, which can lead to missing libraries or other problems when installing packages globally.

Using pipx helps in this case because it installs Python applications in isolated environments, avoiding conflicts with the system Python. Similarly, using pip within a virtual environment can also prevent these issues by creating an isolated space for package installations. However, since pooltool is as much a python package as it is an application, installing with pipx would be inadvisable for many of its use cases.

**Comment by gingerbeardman** [comment]
Understood. 

Advice how to proceed or resolve macOS issues with pip would be appreciated.

**Comment by ekiefl** [comment]
Sure. You want to separate your business with virtual python environments, i.e. environments that are separate from each other and from the system-level python that mac has. The most canonical options are venv and conda. Here is a shameless copy-paste GPT4o response on getting started with either:

Here are two options for creating virtual Python environments, using both `venv` and `conda`:

### Option 1: Using `venv` (Built-in Python Tool)
`venv` is a built-in Python module that comes with Python 3.3 and later. It allows you to create lightweight virtual environments where each environment has its own isolated Python interpreter and set of libraries.

#### Steps:
1. **Install Python**: Ensure that you have Python installed. You can check by running:
   ```bash
   python --version
   ```
   If Python isn't installed, download and install it from the [official Python website](https://www.python.org/downloads/).

2. **Create a virtual environment**:
   - Navigate to the directory where you want to create the virtual environment, then run:
     ```bash
     python -m venv myenv
     ```
     This creates a folder named `myenv` with a copy of the Python interpreter and a blank environment.

3. **Activate the virtual environment**:
   - On **Windows**:
     ```bash
     myenv\Scripts\activate
     ```
   - On **macOS/Linux**:
     ```bash
     source myenv/bin/activate
     ```

4. **Install dependencies**: Once the environment is active, you can install Python packages using `pip`:
   ```bash
   pip install package_name
   ```

5. **Deactivate the environment**: To exit the virtual environment, simply run:
   ```bash
   deactivate
   ```

### Option 2: Using `conda` (Anaconda/Miniconda Environment Manager)
`conda` is a package and environment manager that works not only for Python but also for other languages like R. It allows you to create isolated environments with specific versions of Python and libraries.

#### Steps:
1. **Install Conda**:
   - Install [Miniconda](https://docs.conda.io/en/latest/miniconda.html) or the full [Anaconda distribution](https://www.anaconda.com/products/individual), which includes many scientific packages by default.

2. **Create a conda environment**:
   - To create a new environment, run:
     ```bash
     conda create --name myenv python=3.x
     ```
     Replace `3.x` with the Python version you want to use. This will set up an environment named `myenv`.

3. **Activate the conda environment**:
   - Run the following command to activate the environment:
     ```bash
     conda activate myenv
     ```

4. **Install dependencies**:
   - You can install packages via `conda` or `pip`:
     ```bash
     conda install package_name
     ```
     or 
     ```bash
     pip install package_name
     ```

5. **Deactivate the environment**:
   - To exit the environment, run:
     ```bash
     conda deactivate
     ```

6. **Remove the environment** (Optional):
   - If you want to delete the environment, use:
     ```bash
     conda remove --name myenv --all
     ```

---

Both `venv` and `conda` provide isolated environments, but `conda` is more powerful for managing dependencies and cross-language packages. `venv` is simpler and comes with Python by default, making it a good option for smaller projects or when you only need Python-specific libraries.

**Comment by gingerbeardman** [comment]
I appreciate that those are the recommended ways to do it. But, wow that's a lot of busy work for gains I will never, ever see.

So, honestly, I'll just stick to `pipx pooltool` literally two words.  
Of course, I don't use pooltool as a framework I just play it as a game.

**Comment by ekiefl** [comment]
My advice is unrelated to pooltool and is more about improving your computational literacy around the Python ecosystem. Being able to spin up python virtual environments is not a skill you will regret having.

Bringing this back to pooltool, it would be great to have a "double click to install" option that drew in less computational folk. I notice you've made a Stapler app. Not to put you on the spot, but do you think you would be able to create a macOS package installer for pooltool? I have no idea how any of that stuff works. Is that something you have the bandwidth for?

Until then, I concur `pipx` is not a bad solution.

**Comment by gingerbeardman** [comment]
For Python + Qt apps I've created (venv) I used [pyinstaller](https://pyinstaller.org) to build an app from my code.

Here's the shell script I arrived at to generate the spec file
```
#!/usr/bin/env zsh

pyinstaller -y --onedir --windowed --add-data "/opt/homebrew/bin/aubio:aubio" --add-data "/Users/matt/.matplotlib:matplotlib" --osx-bundle-identifier com.gingerbeardman.beatbox --name Beatbox --icon "icon.icns" gui.py
```

then it's easy to build from the spec for every subsequent change
```
#!/usr/bin/env zsh

pyinstaller -y Beatbox.spec
echo "Removing old app..."
rm -rf /Applications/Beatbox.app
echo "Installing new app..."
mv ./dist/Beatbox.app /Applications/Beatbox.app
open /Applications/Beatbox.app
```

my requirements.txt
```
PyQt6
numpy
matplotlib
sounddevice
configparser
pyinstaller
pyinstaller_versionfile
```
