### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by reynoldsnlp** [ekiefl/pooltool#24]
I can't figure out how the controls work. It might be helpful to have a `Controls` page on the main menu to explain how to adjust all of the parameters and then actually take a shot.

**Comment by ekiefl** [comment]
Hi @reynoldsnlp great point.

It seems like this project is beginning to attract non-zero levels of traffic. I didn't imagine that would happen so soon, but I will prioritize some playing instructions.

By the way, may I ask how you found this project?

**Comment by reynoldsnlp** [comment]
Thanks! I just googled something like "open source pool physics". I'm mostly interested in using this for entertainment/training.

**Comment by ekiefl** [comment]
> I just googled something like "open source pool physics"

I'm really happy to hear that, @reynoldsnlp.

----------------------------

I added some help text that can be toggled in game by pressing 'h'.

![image](https://user-images.githubusercontent.com/8688665/143968570-d6e41475-f729-4da2-b843-a29be69eb430.png)

One day I'll create a proper menu and text system, but for now this should help trailblazers such as yourself at least understand the basic controls to begin experimenting.

The changes can be seen in [this PR](https://github.com/ekiefl/pooltool/pull/26) and have been merged with the main branch. Assuming you followed something resembling the 'Developer' installation instructions, you can pull the latest changes and test things out.

PS modify `pooltool/config/settings` to change the graphical settings.
