### ISSUE TITLE
Any plan to support Snooker?

### ISSUE THREAD

**Issue by timiil** [ekiefl/pooltool#31]
Hi, it is a great project, do you have any plan to support Snooker ?

**Comment by ekiefl** [comment]
Hi @timiil. I certainly plan to support Snooker. No timeline on that but since you're interested I'll prioritize it. Thanks for taking a look at the project.

**Comment by timiil** [comment]
> Hi @timiil. I certainly plan to support Snooker. No timeline on that but since you're interested I'll prioritize it. Thanks for taking a look at the project.

So great , So nice :)

**Comment by LittleWhited01** [comment]
hi,do you support jump ball?

**Comment by ekiefl** [comment]
Closing this issue, because snooker is now (partially) supported (https://github.com/ekiefl/pooltool/pull/99)
