### ISSUE TITLE
Non-frictionless ball-ball collision

### ISSUE THREAD

**Issue by wxmodz** [ekiefl/pooltool#46]
when is Elastic, instantaneous coming? been waiting for it from long

**Comment by ekiefl** [comment]
Context from https://ekiefl.github.io/2020/04/24/pooltool-theory/#section-ii-ball-ball-interactions:

> This section is dedicated to the collision physics between two balls.
>
>When physically modelling a phenomenon, the sky is the limit in terms of how real you want to get. In consideration of the ball-ball interaction, a complete classical description would entail treating the balls as compressible objects–perhaps even modelling the pressure waves that emanate within each ball during a collision. Perhaps this treatment is most necessary during the break shot, and I would be very interested to know how the degree of realism of such a treatment compares to the more pragmatic approaches I will be taking. Speaking of which, here are the two models I will present:
>
>Elastic, instantaneous, frictionless
>Elastic, instantaneous (TODO)
>
>In each of these models, multi-ball collisions are not considered, i.e. each interaction is pairwise.

Eventually I want to focus on improving the physics, but I have no time estimate for you. Pull requests are welcome.

**Comment by ekiefl** [comment]
Solved in https://github.com/ekiefl/pooltool/pull/153
