### ISSUE TITLE
Windows issue list?

### ISSUE THREAD

**Issue by anonymous7002** [ekiefl/pooltool#50]
Should you perhaps put up a list of all the issues on Windows, the choice of over 80% of desktop users, to make us aware of what works and what doesn't?

Are you aware of these, for example:

Permission denied for Temp when taking next shot
List index out of range when flicking mouse too quickly

**Comment by anonymous7002** [comment]
Can't you fork panda3d with relative mouse mode for your own use?

**Comment by ekiefl** [comment]
I'll see if there is a work around, but it seems like a lot of work to fork panda3d.

**Comment by ekiefl** [comment]
I've cleaned up the Windows compatibility. Everything now works except for relative mouse mode, so we're still waiting for 1.11
