### ISSUE TITLE
get_eight_ball_rack is broken

### ISSUE THREAD

**Issue by HorseEars** [ekiefl/pooltool#74]
`line 183, in center_by_table self.balls[-1].R,
AttributeError: 'Ball' object has no attribute 'R'`

It looks like line 183 should be `self.balls[-1].params.R`. I don't know pooltool well enough yet to know if this is my mistake or a missed refactoring issue.

**Comment by ekiefl** [comment]
Hey @HorseEars, thanks for the report. I've fixed this. Let me know if you find other bugs or if you're interested in contributing.
