### ISSUE TITLE
Panda3d 1.10.13 relative mouse mode workaround

### ISSUE THREAD

**Issue by owenhayman** [ekiefl/pooltool#95]
Panda3D 1.10.13's "relative" mouse mode does not work on Windows. I can see from [this panda3d issue](https://discourse.panda3d.org/t/is-mouse-relative-mode-on-windows-still-an-issue/27617) that @ekiefl is already familiar with the problem and has previously reached out to the maintainers. To date, panda3d 1.11.0 is yet to be released.

Despite being unreleased, Panda3d's [install instructions](https://github.com/panda3d/panda3d#installing-panda3d) detail a user-friendly way to install the current dev build of 1.11.0 using pip:

`pip install --pre --extra-index-url https://archive.panda3d.org/ panda3d`

In order to install the dev build of panda3d, I first needed to uninstall the existing version:

`pip uninstall panda3d -y`

From my (very limited) testing, it seems that "panda3d-1.11.0.dev3179" works as a drop-in replacement for 1.10.13. It solves the relative mouse error, and from what I can tell as a new user, the tool seems to work as intended. It's obviously bad practice to take dependency on pre-release versions of software, but as a workaround that brings usability back to a whole platform I think the install instructions can be updated with the above information. I'd say that the GUI can be considered to support Windows, 
 with the caveat that the workaround relies on a potentially unstable pre-release version of panda3d.

Obviously this requires further testing to ensure that it doesn't break existing functionality - but at least for me, this allows me to use the tool and hopefully get familiar enough to start modifying & contributing to the codebase 😄.

**Comment by ekiefl** [comment]
Hey @owenhayman,

Thanks a lot for this great fix. I think this will help a lot of people who are trying to use pooltool on Windows. I've made the change in the install instructions with [this commit](https://github.com/ekiefl/pooltool/commit/5b09783a0152a23749292b8cdf1763d3fdc4c88a).

Also, I added a link to the developers discord in the README [here](https://github.com/ekiefl/pooltool/commit/1ea19614425977f3024857b660cc859f15f6e4bf). If you want to develop for pooltool, consider joining. Cheers.
