### ISSUE TITLE
Asymmetrical behaviour in Han cushion code

### ISSUE THREAD

**Issue by tailuge** [ekiefl/pooltool#96]
Is the modulo on your calculation of Phi losing the y direction sign information in this line ?

`phi = math.angle(rvw_R[1]) % (2 * np.pi)` is always a +ve quantity

https://github.com/ekiefl/pooltool/blob/66ca84c5b27fc9c7bb50187e0fbac634d2540a5d/pooltool/physics/resolve/ball_cushion/han_2005/model.py#L33

I set up a test case bouncing a ball to two symmetrically equivalent directions and observed that the outcomes were not matching. This led me to remove the modulo in my version of the code.

https://tailuge.github.io/billiards/dist/diagrams/symmetry.html

https://github.com/tailuge/billiards/blob/c5aa067cc4caf444cc2057d72ae69b3349a3e1bc/src/model/physics/physics.ts#L108

Let me know if I am wrong about this, thanks in advance.
Luke

**Comment by ekiefl** [comment]
Hey tailuge,

Thanks for reaching out.

> phi = math.angle(rvw_R[1]) % (2 * np.pi) is always a +ve quantity

Well I noticed that `math.angle(...)` itself always returns a positive value:

```python
>>> import numpy as np
>>> import pooltool.math as math
>>> any([math.angle(np.random.randint(-10,10, size=3)) < 0 for _ in range(10000)])
False
```

So in my case, the modulo is not collapsing directionality in the y-direction. Probably because `math.angle` is different than arctan2:

```python
@jit(nopython=True, cache=const.numba_cache)
def angle(v2, v1=(1, 0)):
    """Returns counter-clockwise angle of projections of v1 and v2 onto the x-y plane

    (just-in-time compiled)
    """
    ang = np.arctan2(v2[1], v2[0]) - np.arctan2(v1[1], v1[0])

    if ang < 0:
        return 2 * np.pi + ang

    return ang
```

As for the difference between my code and yours, I'm not sure. I could be accounting for direction in some other way during my coordinate rotation?

> I set up a test case bouncing a ball to two symmetrically equivalent directions and observed that the outcomes were not matching

I assume you discovered this in _your_ project, not pooltool, right?

In general, testing for symmetrical equations is a good idea. I am on vacation but you've prompted me to start thinking about adding such a test. It could cover the Han model and all future models. Maybe I could make a `test_ball_cushion.py` in `pooltool/physics/resolve/ball_cushion/` and maybe it would look something like this:

```python
import pytest
import attrs
from pooltool.system.datatypes import System
from pooltool.physics.resolve.ball_cushion import BallLCushionModel, get_ball_lin_cushion_model
from pooltool.physics.resolve.resolver import Resolver

@pytest.mark.parametrize("model_name", [BallLCushionModel.HAN_2005])
def test_symmetry(model_name) -> None:
    shot = System.example
    
    model = get_ball_lin_cushion_model(model_name)
    resolver = attrs.evolve(Resolver.default, ball_linear_cushion=model)

    # Simulate the shot and the reflected shot, assert isomorphic trajectories
```

I guess I will keep this issue open until I add symmetric physics tests, but as of yet I don't think this is a pooltool bug.

**Comment by tailuge** [comment]
You make a good point that in your code Math.angle is always positive so the modulo makes no difference. I only noticed the problem in my implementation but I think the principle is the same that we rotate the ball to always bounce in +X cushion.

Adding a test is a good idea, the problem is apparent when the ball bounces at a shallow angle with 'slip' i.e. when Pzs > Pze.

My test case that broke without the correction is this one:

https://github.com/tailuge/billiards/blob/ade19d03c726bc414c3c4971fe1241dd029decc1/test/model/cushion.spec.ts#L192

**Comment by ekiefl** [comment]
Ok I hear you. Nice test set by the way, maybe I should use it as a template for my own test set. 

In the example you link, you set vx and vy. Does the ball have any spin or is that, along with the parameters you set, all that's required for the slipping case?

**Comment by tailuge** [comment]
In that test there is no spin i.e. rvel=(0,0,0) this results in a slipping cushion bounce.

**Comment by ekiefl** [comment]
Ok great, thanks.

I'm really interested to hear about your project by the way. So nice you can play it on the browser!

**Comment by tailuge** [comment]
I have worked on and off on my implementation for years, but only this year I read your blog and the corrections you pointed out on the Han paper (I've referenced you in the readme). Thank you for posting that, I feel like it gave me a big breakthrough in the physics model.

**Comment by tailuge** [comment]
The only benefit of running in a browser is you can send someone a link to [your break](https://tailuge.github.io/billiards/dist/?ruletype=nineball&state=%7B%22init%22:%5B-0.6765,0,0.661,-0.001,0.719,0.033,0.721,-0.033,0.778,0,0.779,-0.068,0.779,0.068,0.836,0.033,0.838,-0.034,0.897,0.002%5D,%22shots%22:%5B%7B%22type%22:%22AIM%22,%22offset%22:%7B%22x%22:-0.009,%22y%22:0.129,%22z%22:0%7D,%22angle%22:0,%22power%22:3.69,%22pos%22:%7B%22x%22:-0.6765,%22y%22:0,%22z%22:0%7D,%22i%22:0%7D,%7B%22type%22:%22AIM%22,%22offset%22:%7B%22x%22:0,%22y%22:-0.181,%22z%22:0%7D,%22angle%22:-1.462,%22power%22:3.69,%22pos%22:%7B%22x%22:1.2359025296756407,%22y%22:0.4528025334442929,%22z%22:0%7D,%22i%22:0%7D,%7B%22type%22:%22AIM%22,%22offset%22:%7B%22x%22:0.3,%22y%22:-0.013,%22z%22:0%7D,%22angle%22:-1.788,%22power%22:1.439,%22pos%22:%7B%22x%22:-0.9104082526666236,%22y%22:0.5944468764214577,%22z%22:0%7D,%22i%22:0%7D,%7B%22type%22:%22AIM%22,%22offset%22:%7B%22x%22:-0.022,%22y%22:-0.299,%22z%22:0%7D,%22angle%22:0.186,%22power%22:2.546,%22pos%22:%7B%22x%22:-0.09819477702980065,%22y%22:0.2870354766220989,%22z%22:0%7D,%22i%22:0%7D,%7B%22type%22:%22AIM%22,%22offset%22:%7B%22x%22:-0.022,%22y%22:-0.299,%22z%22:0%7D,%22angle%22:-0.786,%22power%22:2.546,%22pos%22:%7B%22x%22:0.31259415898184756,%22y%22:0.31038118889699945,%22z%22:0%7D,%22i%22:0%7D,%7B%22type%22:%22AIM%22,%22offset%22:%7B%22x%22:-0.026,%22y%22:0.095,%22z%22:0%7D,%22angle%22:-1.734,%22power%22:2.546,%22pos%22:%7B%22x%22:-0.16714252936068394,%22y%22:0.26436565968923337,%22z%22:0%7D,%22i%22:0%7D,%7B%22type%22:%22AIM%22,%22offset%22:%7B%22x%22:-0.225,%22y%22:0.198,%22z%22:0%7D,%22angle%22:0.556,%22power%22:3.69,%22pos%22:%7B%22x%22:-0.10530082293504821,%22y%22:-0.19078177741225832,%22z%22:0%7D,%22i%22:0%7D,%7B%22type%22:%22AIM%22,%22offset%22:%7B%22x%22:0.155,%22y%22:-0.241,%22z%22:0%7D,%22angle%22:0.104,%22power%22:3.69,%22pos%22:%7B%22x%22:0.05479569126909734,%22y%22:-0.6215092135546808,%22z%22:0%7D,%22i%22:0%7D%5D%7D)

**Comment by ekiefl** [comment]
> Thank you for posting that, I feel like it gave me a big breakthrough in the physics model.

You're very welcome, I'm glad you found it.

I added symmetric tests for a variety of incoming angles. This includes cases where the Han model slips. The test lives in `test_ball_cushion.py` and can be applied to all existing ball-cushion models.

By the way, if you want to collaborate or bounce ideas off one another, you should join the developer discord: https://discord.gg/jAbQRWR3
